#████████╗██╗███╗░░░███╗░█████╗░███╗░░██╗███████╗██╗░░██╗░█████╗░░██████╗
#╚══██╔══╝██║████╗░████║██╔══██╗████╗░██║██╔════╝██║░██╔╝██╔══██╗██╔════╝
#░░░██║░░░██║██╔████╔██║███████║██╔██╗██║█████╗░░█████═╝░██║░░██║╚█████╗░
#░░░██║░░░██║██║╚██╔╝██║██╔══██║██║╚████║██╔══╝░░██╔═██╗░██║░░██║░╚═══██╗
#░░░██║░░░██║██║░╚═╝░██║██║░░██║██║░╚███║███████╗██║░╚██╗╚█████╔╝██████╔╝
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚══════╝╚═╝░░╚═╝░╚════╝░╚═════╝░
#
#plugin by timur rootkovskiy
#www.rootkovskiy.ovh
#
PREFIX: "&4(&eКошкоДевочки&4) &r"
#
NO_PERMS: "&eУ вас нет прав"
#
NO_PLAYER: "&eВы не можете использовать эту команду, потому что вы не игрок"
#
INVALID_USAGE: "&eНеправильное использование - &4/neko [on/off/reload]"
#
NEKO_ON: "&eВы вошли в режим кошкодевочки"
#
NEKO_OFF: "&eВы вышли из режима кошкодевочки"